FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libcurl4-openssl-dev pkg-config libssl-dev openssl zlib1g-dev make gcc

COPY . /hcxtools
WORKDIR /hcxtools
RUN make -j8
RUN make install DESTDIR=/install

FROM ubuntu:20.04 as package
COPY --from=builder /install /install
